### ISSUE TITLE
How to customize blog post URL by modifying the folder name?

### ISSUE THREAD

**Issue by sharduul** [arshad/gatsby-themes#46]
My blog folder naming convention is -

`MMDDYYYY-name-of-the-post`

This translates into URL for that post being `/posts/MMDDYYYY-name-of-the-post`

I want to remove the date part from the URL. I want to change the URL to -

`posts/name-of-the-post`

(for SEO reasons)

I am trying to modify the `gatsby-node.js` like below.

```

exports.onCreateNode = async ({ node, actions, getNode }) => {
  if (node.internal.type !== `Post` || node.internal.type !== `Mdx`) {
    return;
  }

  const value = createFilePath({ node, getNode }).replace(/\d{6}-/, "");
  const { createNodeField } = actions;

  createNodeField({
    name: `slug`,
    node,
    value,
  });
};

```

But, it is not changing the URL.

Any idea what could be wrong?

**Comment by arshad** [comment]
The slug is generated in `https://github.com/arshad/gatsby-themes/blob/master/core/gatsby-theme-blog-core/gatsby-node.js#L76` which is way before your theme's `gatsby-node.js` is run.

This is a valid request though. Let me see if we can make this customizable in the theme.

As a temp fix, you can provide a `slug` value in your blog post markdown file:

```md
---
title: Name of Blog Post
slug: name-blog-post
---
```

**Comment by mattmaker** [comment]
@sharduul Are you trying to keep the date in the folder name while removing it from the URL?

**Comment by sharduul** [comment]
@mattmaker - yes that is correct.

@arshad - thank you for the workaround. That worked. Although, I would really appreciate if we could have the ability to override the slug `gatsby-node.js` as a more scalable and cleaner approach.

**Comment by arshad** [comment]
@sharduul @mattmaker Finally got some time to work on this today. I added a `slugResolver` option. You can use it as follows:

```
{
  resolve: `@arshad/gatsby-theme-blog-core`,
  options: {
    slugResolver: (node, parentNode) => custom_slug(node.title)
  }
},
```

- **node** is the *Post* node (so you get access to `title`, `date` and any frontmatter fields).
- **parentNode** is the *Mdx* node (so you can access the relative directory..etc).

This is opt-in. If you do not provide a `slugResolver` the default is used. No breaking change.

Added this to the README as well: https://github.com/arshad/gatsby-themes/tree/master/core/gatsby-theme-blog-core#slug

Let me know if this works.

**Comment by sharduul** [comment]
Sorry for the late response.

I was trying this today and I am getting this error

```
[ { Error: Cannot return null for non-nullable field Post.slug.
      at completeValue (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:560:13)
      at completeValueCatchingError (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:495:19)
      at resolveField (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:435:10)
      at executeFields (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:275:18)
      at collectAndExecuteSubfields (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:713:10)
      at completeObjectValue (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:703:10)
      at completeValue (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:591:12)
      at completeValue (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:557:21)
      at completeValueCatchingError (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:495:19)
      at /Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:618:25
      at Array.forEach (<anonymous>)
      at forEach (/Users/sbagade/repo/chalk2/node_modules/iterall/index.js:83:25)
      at completeListValue (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:614:24)
      at completeValue (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:573:12)
      at completeValue (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:557:21)
      at completeValueCatchingError (/Users/sbagade/repo/chalk2/node_modules/graphql/execution/execute.js:495:19)
    message: 'Cannot return null for non-nullable field Post.slug.',
    locations: [ [Object] ],
    path: [ 'allPost', 'posts', 0, 'slug' ] } ]


 ERROR 

There was an error fetching blog posts. Cannot return null for non-nullable field Post.slug.

```

am I missing something?

**Comment by sharduul** [comment]
After a lot of debugging, I found the fix for the above error

```
slugResolver: (node, parentNode) => {
  return node.frontmatter.title;
},
```

But, when I go to my post I am getting another error

```
Gatsby.js development 404 page
There's not a page yet at /blog/what-is-js

Preview custom 404 page

Create a React.js component in your site directory at src/pages/blog/what-is-js.js and this page will automatically refresh to show the new page component you created.

If you were trying to reach another page, perhaps you can find it below.

```

I don't know why is it searching for `src/pages/blog/what-is-js.js`

My folder structure is like this

![Screen Shot 2020-10-12 at 11 05 56 PM](https://user-images.githubusercontent.com/4227876/95821793-7da2e580-0cdf-11eb-9265-b86b96c77531.png)
